// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package registry

import (
	"github.com/myohei/employee-manager-go/internal/employee/app"
	"github.com/myohei/employee-manager-go/internal/employee/infra/inmemory"
	"github.com/myohei/employee-manager-go/internal/interfaces"
)

// Injectors from wire.go:

func InitCLI() *interfaces.CLI {
	employeeRepo := inmemory.NewEmployeeRepo()
	createEmployee := app.NewCreateEmployee(employeeRepo)
	showEmployee := app.NewShowEmployee(employeeRepo)
	deleteEmployee := app.NewDeleteEmployee(employeeRepo)
	cli := interfaces.NewCLI(createEmployee, showEmployee, deleteEmployee)
	return cli
}

// wire.go:

var appSuperSet = app.SuperSet

var inmemorySuperSet = inmemory.SuperSet
